Update demo.rs
Quick fix for demo.

Rustc error was:
error[E0502]: cannot borrow `*app` as mutable because it is also borrowed as immutable
   --> examples/demo.rs:437:63